### ISSUE TITLE
Math !

### ISSUE THREAD

**Issue by VinhNguyen309** [kpcyrd/nude-rs#2]
Hi,

I am very excited with your project but I'm quite confused about the formulas you use.
![Capture](https://user-images.githubusercontent.com/23103499/57676668-4003de00-764f-11e9-9417-2af025e6ba76.PNG)

You can share your's paper use in this project.
Thanks !

**Comment by kpcyrd** [comment]
This is a direct translation of:

https://github.com/pa7/nude.js/blob/5a0b01f39a381132ddb592235de0690e3e68e961/worker.nude.js#L334-L354

I assume this function is `2.2.2.The HSV (HSI, HSL) Color Space` from the paper:

https://be82ac79-a-aff4c786-s-sites.googlegroups.com/a/dcs.upd.edu.ph/csp-proceedings/Home/pcsc-2005/AI4.pdf?attachauth=ANoY7cogSen4_Janmf78cvzN-a3hK5pdsDpgjG0gDwcO_-9pryf75CEGsLAti82TMWDUb6tGvyolK2ZI6oCk1pUbXbhS8NBiHP1JhpwZtM8Sy37m9xBvoyNfT-aPVmAcsdUB30hiOlfsIsaAAuKa3nHXRLEon_4cXVoHHRzh7Nc3IFr92L-VWEbqT27AvwTko48gQuaakrc7_yv-mKQ8C2oYODUFkzIuKgPnwQeu515KkS1myVVYsXI%3D&attredirects=0

**Comment by VinhNguyen309** [comment]
ohhh, it so helpfull , thanks bro ^^
