### ISSUE TITLE
Readme link to paper fail

### ISSUE THREAD

**Issue by Elphikaus** [kpcyrd/nude-rs#5]
From the README.md, the link to the paper is not working, also it would be helpful to have the title of rte paper as well. 

Thanks. 

[0]: https://sites.google.com/a/dcs.upd.edu.ph/csp-proceedings/Home/pcsc-2005/AI4.pdf?attredirects=0

**Comment by kpcyrd** [comment]
Thanks, I've changed it to an archive.org link.
